<p style='text-align:center'>
PSY 394U <b>Methods for fMRI</b>, Fall 2018


<img style='width: 300px; padding: 0px;' src='https://github.com/sathayas/JupyterfMRIFall2018/blob/master/Images/Placebo_Left.png?raw=true' alt='brain blobs'/>

</p>

<p style='text-align:center; font-size:40px; margin-bottom: 30px;'><b>NumPy arrays, image data</b></p>

<p style='text-align:center; font-size:18px; margin-bottom: 32px;'><b>September 17, 2018</b></p>

<hr style='height:5px;border:none' />

# NumPy arrays
<hr style="height:1px;border:none" />

## Creating an array
An array is a data type available in **`NumPy`**. It is similar to a list, but much more
versatile than a list, and especially useful for scientific data.

In [2]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

Note that when we import **`numpy`**, we assign a name **`np`**, so that we don't have to
type `numpy` every time we call a function in the `numpy` module. An array can be
converted to a list, or vice versa.

In [2]:
list(a)

[1, 2, 3, 4, 5]

In [3]:
b = [10, 9, 8, 7, 6]
np.array(b)

array([10,  9,  8,  7,  6])

An array can be two dimensional. For example,

In [4]:
c = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

You can examine the shape of an array using the **`ndim`** method (to examine
dimension), the **`shape`** method (to examine the size in each dimension), and the
**`size`** method (to examine the total number of elements).

In [5]:
c.ndim

2

In [6]:
c.shape

(4, 3)

In [7]:
c.size

12

This tells us that the array `c` is two-dimensional, with 4 rows and 3 columns, and
has 12 elements.

In practice, you usually do not enter elements one by one. Here are some useful
functions. First an array of ones with **`np.ones()`** function.

In [8]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

And an array of zeros with **`np.zeros()`** function.

In [9]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

You can change the shape of an array with the **`reshape()`** method. An array of 15 numbers are reshaped into different 2D arrays.

In [10]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
b = a.reshape(3,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## Working with an array

Unlike lists, arrays can be used in mathematical operations. For example,

In [12]:
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
b = np.ones((3,3))
b = np.arange(9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
a + b

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [15]:
a * b

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

An operation involving arrays is performed on element-by-element basis. You can also perform an operation between an array and a scalar (i.e., a single number). In such a case, each element in the array is used in an operation with a scalar.

In [16]:
a + 10

array([[11., 11., 11.],
       [11., 11., 11.],
       [11., 11., 11.]])

In [17]:
5 * a

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

Of course, you can perform a matrix-like operations as well. First, you can transpose a matrix with **`T`**. 

In [12]:
B = np.array([[1,2,3],[3,2,2],[0,1,1]])
B

array([[1, 2, 3],
       [3, 2, 2],
       [0, 1, 1]])

In [13]:
B.T

array([[1, 3, 0],
       [2, 2, 1],
       [3, 2, 1]])

Here is a matrix multiplication by the **`np.dot()`**.

In [14]:
V = np.arange(1,4).reshape(3,1)
V

array([[1],
       [2],
       [3]])

In [15]:
np.dot(B,V)

array([[14],
       [13],
       [ 5]])

And finally the inverse matrix by the **`np.linalg.inv()`** function. 

In [16]:
invB = np.linalg.inv(B)
invB

array([[ 0.        ,  0.33333333, -0.66666667],
       [-1.        ,  0.33333333,  2.33333333],
       [ 1.        , -0.33333333, -1.33333333]])

In [17]:
np.dot(invB,B)

array([[ 1.00000000e+00, -1.11022302e-16, -1.11022302e-16],
       [-5.55111512e-17,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

## Useful methods

Here are some useful methods for arrays. First, finding the maximum with the **`max`** method. You can find the maximum for the entire array.

In [18]:
a = np.random.rand(4,3)
a

array([[0.59006127, 0.41179204, 0.79269959],
       [0.88733431, 0.34125123, 0.5207373 ],
       [0.36439625, 0.63497422, 0.82594762],
       [0.24121594, 0.53369929, 0.2679379 ]])

In [19]:
a.max()

0.8873343050623193

Or for each row

In [20]:
a.max(axis=1)

array([0.79269959, 0.88733431, 0.82594762, 0.53369929])

Or for each column

In [22]:
a.max(axis=0)

array([0.88733431, 0.63497422, 0.82594762])

Similarly, you can use the **`min`** method to find the minimums.

In [23]:
a.min()

0.24121594315036776

In [24]:
a.min(axis=1)

array([0.41179204, 0.34125123, 0.36439625, 0.24121594])

In [25]:
a.min(axis=0)

array([0.24121594, 0.34125123, 0.2679379 ])

And you can calculate the sum of an array with the **`sum`** method.

In [26]:
a.sum()

6.41204695705383

In [27]:
a.sum(axis=1)

array([1.79455289, 1.74932284, 1.82531809, 1.04285313])

In [28]:
a.sum(axis=0)

array([2.08300776, 1.92171679, 2.40732241])

## Indexing and slicing

You can index and slice an array just the same way as a list.

In [29]:
x = np.arange(10)**2
x

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [30]:
x[4]

16

In [31]:
x[4:]

array([16, 25, 36, 49, 64, 81])

In [32]:
x[-3:]

array([49, 64, 81])

Unlike a list, you can also have a list of indices to access elements as well.

In [34]:
x[[1,3,7,8]]

array([ 1,  9, 49, 64])

In [35]:
x[[1,1,1,9]]

array([ 1,  1,  1, 81])

For a 2D array, the first index corresponds to the row, and the second index
corresponds to the column. If you ignore the second index, then the entire row is
returned. Both row and column indices can be a number (i.e., index) or a slice.

In [36]:
b = np.arange(15).reshape(3,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [37]:
b[1]

array([5, 6, 7, 8, 9])

In [38]:
b[2,3]

13

In [39]:
b[1:,3:]

array([[ 8,  9],
       [13, 14]])

And, you can use a list for row indices or column indices as well.

In [40]:
b[1:,[1,1,3,3,2]]

array([[ 6,  6,  8,  8,  7],
       [11, 11, 13, 13, 12]])

In [41]:
b[[1,1,0],2:]

array([[7, 8, 9],
       [7, 8, 9],
       [2, 3, 4]])

In [42]:
b[[0,1,0,2,1],[1,1,3,3,2]]

array([ 1,  6,  3, 13,  7])

## Conditional indexing

With an array, it is easy to generate a sub-array satisfying certain conditions. For
example, lets say you have the following data.

`<ExampleData.py>`

In [43]:
import numpy as np

subjID = np.array(['sub001']*3 + ['sub005']*4 + ['sub010']*3)
RT = np.array([ 98,  96,  86,  90,  95,  80, 117,  90, 114, 113])
score = np.array([0, 0, 1, 0, 1, 0, 0, 0, 1, 0])

print('ID\tRT\tScore')
for i,iID in enumerate(subjID):
    print(iID, RT[i], score[i], sep='\t')

ID	RT	Score
sub001	98	0
sub001	96	0
sub001	86	1
sub005	90	0
sub005	95	1
sub005	80	0
sub005	117	0
sub010	90	0
sub010	114	1
sub010	113	0


Then you can create sub-arrays based on a particular subject ID.

In [44]:
subjID[subjID=='sub005']

array(['sub005', 'sub005', 'sub005', 'sub005'], dtype='<U6')

In [45]:
RT[subjID=='sub005']

array([ 90,  95,  80, 117])

In [46]:
score[subjID=='sub005']

array([0, 1, 0, 0])

You can use technique on 2D arrays as well.

In [47]:
dMat = np.array([[ 94, 116, 104, 97, 99],
[ 92, 107, 92, 103, 104],
[115, 112, 81, 90, 90],
[ 94, 100, 90, 92, 114]])

dMat[dMat>95]

array([116, 104,  97,  99, 107, 103, 104, 115, 112, 100, 114])

Notice that it returns a 1D array.

If you just write a condition, then it will return an array of True and False.

In [49]:
dMat>95

array([[False,  True,  True,  True,  True],
       [False,  True, False,  True,  True],
       [ True,  True, False, False, False],
       [False,  True, False, False,  True]])

### Exercise
**Mean RTs and scores**. You have two arrays of the same size.

`<RTData.py>`

In [48]:
import numpy as np

RTMat = np.array([[111, 100,  86, 120,  91],
                  [ 92,  83, 105, 103, 112],
                  [117, 121, 124, 111, 110],
                  [111,  86, 113,  88, 105]])
scoreMat = np.array([[1, 0, 0, 0, 0],
                     [0, 1, 1, 0, 1],
                     [0, 1, 1, 0, 0],
                     [0, 0, 1, 1, 0]])

where **`RTMat`** corresponds to the response times (RT) in ms and **`scoreMat`**
corresponds to the scores from the same experiment.

1. **Mean RT**. Calculate the mean RT for observations with score =0. Do the same for observations with score = 1.<br>
      ***Hint:*** *You can use the **`mean()`** method for an array*. 
    
2. **Mean score**. Calculate the mean score for observations with `RT`>100ms.

# Image data
<hr style="height:1px;border:none" />
## Data sets

Now that we know how to handle array data in Python, we can take a look at some image data. Brain image data are often saved as 3D arrays (e.g., T1-weighted structural MRI) or 4D arrays (e.g., fMRI time series). For this exercise (and for some future exercises), I would like you to download two publicly available fMRI data sets, available on OpenNeuro.org.

* Flanker task, event related [ds102](https://openneuro.org/datasets/ds000102) (~3.7GB)
* Test-retest data of motor, language, and spatial attention [ds114](https://openneuro.org/datasets/ds000114) (~4.7GB)

Both data sets should be available as gzip tar archives (with **`.tar.gz`** extension). First thing you want to do is to *move the files* to a desired location. For example, I have a directory called **`Data`** under my fMRI course directory. Once the tar files are at the desired location, you can extract the data sets by first unzipping the file.
```
gunzip [downloaded file name.tar.gz]
```
You can skip this process if the downloaded file does not have the **`.gz`** extension (as Mac computers uncompress .gz files during download). Then you un-tar the file by
```
tar -xvf [downloaded file name.tar]
```
***Note***: *These are commands to be executed on the terminal window; they are not Python commands.

This should creates two new directories, each with a complete data set. For the sake of quick and easy access, I recommend changing the directory names to **`ds102`** and **`ds114`** with the **`mv`** command.
```
mv Flanker\ task\ \(event-related\)/ ds102
mv A\ test-retest\ fMRI\ dataset\ for\ motor\,\ language\ and\ spatial\ attention\ functions./ ds114
```

## Reading image data

* List of subjects
* NiBabel - read image

### T1 image

* Image matrix
* Slices (axial, saggital, coronal)
* Maximum intensity projection

### fMRI data

* Plotting time series
* Slices across time
* Subtracting mean

## Writing image data

* Mean & SD images
* Write image


# Image viewer
<hr style="height:1px;border:none" />